services:
  - type: web
    name: nexus-sentinel-advanced-global-security
    env: node
    autoDeploy: true
    buildCommand: npm ci && npm run build
    startCommand: node dist/server.js
    healthCheckPath: /readyz
    # Optional: uncomment to pin a specific plan or region
    # plan: free
    # region: oregon
    # Optional environment variables
    # envVars:
    #   - key: NODE_ENV
    #     value: production
